export const USER_ACTION_TYPES = {
  REGISTER_SUCCESS: "user/REGISTER_SUCCESS",
  REGISTER_FAILED: "user/REGISTER_FAILED",
  USER_LOADED: "user/USER_LOADED",
  AUTH_ERROR: "user/AUTH_ERROR",
  LOGIN_SUCCESS: "user/LOGIN_SUCCESS",
  LOGIN_FAILED: "user/LOGIN_FAILED"
};
