export const PROFILE_ACTION_TYPES = {
  GET_PROFILE: "profile/GET_PROFILE",
  PROFILE_ERROR: "profile/PROFILE_ERROR",
  CLEAR_PROFILE: "profile/CLEAR_PROFILE",
  UPDATE_PROFILE: "profile/UPDATE_PROFILE",
  DELETE_PROFILE: "profile/DELETE_PROFILE"
};
